### ISSUE TITLE
Half-duplex issue on AN/PRC-77

### ISSUE THREAD

**Issue by Omnari** [fparma/fparma-mods#42]
Players can step on each other's transmissions even when on different frequencies. This was first noticed during Operation Ouroboros, where leaders spread across three LR frequencies still triggered the fp half-duplex system when anyone on any frequency talked.

This is likely occurring because the PRC-77 uses raw frequencies instead of channels. For reference, the AN/PRC-77 is the vintage backpack radio alternative to the standard backpack radio. The standard modern backpack radio is the PRC-117 and that one does _not_ suffer this issue.

**Comment by diwako** [comment]
fixed
